version: 1.0.{build}

image: ubuntu

build_script:
  - dotnet build

environment:
  NUGET_API_KEY:
    secure: 0QRcrLmvuSmZgWchRscyCm1btgQQVQPUhM5MWJ3CERMi60yZ2zMqbMx2tnkFqgT9

deploy_script:
  - bash scripts/deploy.sh src/Cake.Vault/Cake.Vault.csproj

artifacts:
  - path: '*.nupkg'

after_build:
  - ps: Get-ChildItem .\*.nupkg | % { Push-AppveyorArtifact $_.FullName -FileName $_.Name }
